openapi: 3.0.0
info:
  title: Petstore
  version: 1.0.27
servers:
  -
    url: /api/v3
paths:
  /pet:
    post:
      summary: addPet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        405:
          description: Invalid input
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
    put:
      summary: updatePet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Pet not found
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /pet/{petId}:
    post:
      summary: updatePetWithForm
      parameters:
        -
          name: petId
          in: path
          required: true
          schema:
            type: integer
        -
          name: name
          in: query
          schema:
            type: string
        -
          name: status
          in: query
          schema:
            type: string
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Pet not found
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
    get:
      summary: getById
      parameters:
        -
          name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        404:
          description: Pet not found
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
    delete:
      summary: deletePet
      parameters:
        -
          name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        400:
          description: Invalid ID
  /pet/findByStatus:
    get:
      summary: findByStatus
      parameters:
        -
          name: status
          in: query
          schema:
            type: string
      responses:
        400:
          description: Invalid status value
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Pet:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        category:
          $ref: "#/components/schemas/Category"
        status:
          type: string
    Order:
      type: object
      properties:
        id:
          type: integer
        petId:
          type: integer
        quantity:
          type: integer
        complete:
          type: boolean
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
        type:
          type: string
        message:
          type: string